
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += timescaleit.v $(WORKSHOPROOT)PixelSolver.v

TOPLEVEL=PixelSolver
MODULE=PixelSolverTester

include $(shell cocotb-config --makefiles)/Makefile.sim